# 以下配置兼容环境变量设置,配置文件优先级高于环境变量
# PROXY: "" # 代理地址 默认值 "",支持http https socks5
REFRESHCOOKIE: "eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..iSzmWZxOOhvr9FQJ.FIlecvxNprsiEmosOGImxiOADbz8Ldi4GtQsGB356NF8LUv4k_NA0BNArFKsyFMydUlaZmrKlUx8Gh1NYG-C6RvX49BsZRSht772U80fihkeGSb65uJ7jRQJGzXZoEPQjGduw91JtiYWLm4JAGftqWiOGVdSvTRYXkAxRbDrCs_eYDv3qfL7KEpqOsJ5m_IYgK-MIrdZgj--9qcAT2TJCHDYSW4JefC-3gKPxK5tVQibkiGOSLhxX11NIjQQu5EgVzHq2xRVpdzB9dDTZv5vlWwRtCm2142snd7gZZQQUyNC0S4lfCsQ7LKwYJ2wbG6Hg5eOddhK2AORbkuBuAbCLcCYrZMtorigTLhvWfH3G5O9KWkX9yUs7Rhq_6ceI1r1n3hNX0sio2a6kFnW-h9L5OCLvLhcS1ud6uVvAltO88zqREO91lSh59MKqc_Q2tEGFU4vgbExYaFwCZ3KfWJeoX9lcY2TJsKSR1GSy8TpnEqp6_59R3FqcM7vO4X1BNpGsYt5J2jKTEZdmO2Sr-ByXJn6SezCEG2lnNxy_pVaoowczy0fQfBSwDCjwyd3C-VskBRor9XXE5iQ3lVlb-lawFChHJXEVcs5RbVAPvi93YX2Do2nmIsLAcEj0Fh9hoSNsAA1ZDCqf_FFLw1Fe9wHi6j2QY3hTNWKHuUgMGZk-6xLo4lEoJ7__c0_a2PMO30gO9kGxbDjjKSxOSz0mEZ6w1YPTwUUmJiIuFBNki7IYMt7tfHb3_eF0utOwBqs8KnO2mldfkTiE9YUEdECQc5APN5GuoJXlMJEQHtleqwpj-YabcavDNdfMAxjOpcfios1CBcgZPSH63gFh4yGZgft-aVxG2GX-MM46rmKJ1qR9g1MzXuTl02Niy6TzxX7wp_XMfVI9-wpvUa4eGbu5KttZO6KcmlylSzBlV_PCAHNTxoYuxDKYd0roLqZN8iVWqnQqfIdUR-IL1HiaSsarFX54Z7qY0Vbf-Pf9Llg2tsRHLVL7vT502yi6OWCPFH8yPflIQNHoLcT75cyTxg9u0k6cUhR_9kNq0K77OIxUcFl-xJeaVkxs8M9vPY0rtk1vriz1mkdZbXxLjFwucvpelOd7XLtXXfTkPiJOb1p8p8HmlzCO1WcfNpmo12uw4nwbI9CmySHtCnZHNWXx1jeKrUJM-mcn6di_jgiiHRbz8uT5Y18ha3AGgK_FmK79G6sKf4dGWnEEToXvdBBc_5r5DeofpVtWlWNvV6uJegE7Y3eG43JLcjdBxfZ9BS5u5otLKKM0d0IpOn0XI1Nxdm5aD4uoqqkgtMXON2AIjPm5M5J7u6e0TJ9XvINJM5tnGrnNqXks19l_HR1Br_aRiQmVC2nKWwR7o64REW4qyJQTf66OLBbQz9DP3eLfP7ZqAcsZQxX4kgX2i9n_V-0wKvqGiyfkYWByYTFtKNOfcnOQMd0-O062dCNPBhrfaWTQzRS4T5n1rloi1NquCBhDPntMFyU_2EO0F0Q0do2FOU2-faVyF2cKIJRhjjjfKB0ZSmFffeCkMWHl0o5qLjJMAikx60me7T1apd7W9U9T5Se99pvtyw5Wap-8rpqldKJFVuZG3OTKMmWl95xHF6WLGGJfxNuVZJE2UYAeddkpyyQiqv8yuDrsbQEXFimO77Kd3xMfnzScLIY4-JSsgj96scerSAU9YafYqBPY2rmVfzbGLkVVdv-hqdAmXWOwojQibsNGUEiWFCqH8oVG-8cGw1Adq_qsZjum0DHdbP9dWX8NlBEK-sjALw2r4_GqiHShY5RGoVs3aQ7ycxSUqS8almZZFYH1JqvlKyZw7hG2WPPDMHQkfYOCtub4kJtYozagWxwHEus2MQpa95u21vdboA_hMP1cACe-obaF2nIhrvOzjl20D4ohvy9ERIHz3FRS9_2Usq6PTm1DVJX9I-bzKp3gaMb6N87sno4Cv9BWbr7Oot1esZVURE56prdX2JUNLpPe3F8cGe7YGXkFAIbqXVBeZ0i3igU_f2G763RLPnXsg4iHKSKzF9eik8s51DoQIpQzQlFbmNuScQIlPn9tBUNKf4vbohiHnHyvW3PNDpkxxVlEqvzjkm7YwuQFD56AvDmOmXILB3rAOepS7DBj0sAmszNqHNodIAVPbep3RmtqAQmO6ifu9eRlCSIs6YOXJqbzpcZZCcjBHuLntJXwYD8NGS7nOG05eF7puH2tRGOoxKWOZpu71dvQ2adEvMLz6hxPQcpi6lBk58Hee1nSPcQRetDbW_I3T4L41qiuk7QhcPeraW4GWWBuELIDVps5-4R4uBbGMBPIwMAPOUXcADq4A3DoWBW3tll0xA2M-KXwDJDK4JkSzZA_n1y_jdykbql3togXFEqfNd3l3DYhnFB35uHNlo7jos70MYKWIedDNFcWkQrH8ttaOxg9cd9Nq3dWclv31dSJyHig70wbgjQaVFow1dirH_T_ksE9CwBqHYo7UWsKYpef5iFa6qQXtdZDvmbKax8bhkqM06DPQe-6rZ57xJw4jnpymg9MPJB4aN6IM9Q4g4eZe8KPfRjjU3QWjqaU0gSZuSj9xi1YkNjBOGELj1hAw9E6gc0yJkg5tGcuGYmTEMnvc6uFD_0OTYU1O2AMr_DRpOwBkhBnjCgCnA74gi1wyysVK2oUPKr9tE3--zyrPxnWZmH3qyZh9-E4cXctPpLHYovuX9M1pT55y4RfirJSOMDCawc5UlXQfXBUiG6gey3-HSyE42oz0L7n01TVadE5unwa3KhG5DrIxmgrQio7gVYVy6VBrglWGLrvJgsg2RUJfR9YPDVF_sSdzI6--mycpPButHijt3RBNB_aOg-9S-6m-QNnhyxgVI8g_k2b80H-SyZM5x_6UkwHDUe_rA1GNVXzXEpu1kHZNZRmJQ1gkgz8B1Y7nl9Rr64IffQWAcfW-GX5rKf.4FiMfyUh_HmusDcgK9deOw"
# OAUTH_URL: https://xxxxx.xxx.com/ouath # oauth地址 用于集成第三方登录 默认值 ""
# LOGIN_CALLBACK: "/login" # 登录回调地址,用于指定自己的登录页面 默认值 "/login"
# ASSET_PREFIX: https://cdn.oaistatic.com # 静态资源前缀,用于指定自己的静态资源地址 默认值 https://oaistatic-cdn.closeai.biz
# ARKOSE_URL: https://tcr9i.chat.openai.com/v2/ # arkose地址,用于指定自己的arkose人机验证地址 默认值 https://tcr9i.closeai.biz/v2/
# ADMIN_PASSWORD: xxxxx # 管理员密码 默认值为随机字符串,每次启动都会变化，可以在启动时通过日志查看，也可以指定一个固定值，方便管理
# AUDIT_LIMIT_URL: https://auditlimit.closeai.biz/audit_limit # 审计限制url 默认值 ""

# 以下配置不兼容环境变量设置,只能通过配置文件设置
USERTOKENS: # 用户token,可配置多个,本项内容支持热更新,更改后即时生效
  - "user1"
  - "user2"

# PROXY: "http://127.0.0.1:31280"  # 代理地址
# OAUTH_URL: https://xxxxx.xxx.com/ouath

# 注意注意,以下为新增配置,如需自动创建数据库,必加以下配置
cool:
  autoMigrate: true


# sqlite数据库配置
database:
  default:
    type: "sqlite" # 数据库类型
    name: "./config/cool.sqlite" # 数据库名称,对于sqlite来说就是数据库文件名
    extra: busy_timeout=5000 # 扩展参数 如 busy_timeout=5000&journal_mode=ALL
    createdAt: "create_time" # 创建时间字段名称
    updatedAt: "update_time" # 更新时间字段名称
    # debug: true # 开启调试模式,启用后将在控制台打印相关sql语句

# mysql数据库配置

# database:
#   default: # 数据源名称,当不指定数据源时 default 为默认数据源
#     type: "mysql" # 数据库类型
#     host: "127.0.0.1" # 数据库地址
#     port: "3306" # 数据库端口
#     user: "root" # 数据库用户名
#     pass: "xxxxxxxxx" # 数据库密码
#     name: "cockroachai" # 数据库名称
#     charset: "utf8mb4" # 数据库编码
#     timezone: "Asia/Shanghai" # 数据库时区
#     # debug: true # 是否开启调试模式，开启后会打印SQL日志
#     createdAt: "createTime" # 创建时间字段
#     updatedAt: "updateTime" # 更新时间字段
