# 以下配置兼容环境变量设置,配置文件优先级高于环境变量
# PROXY: "" # 代理地址 默认值 "",支持http https socks5
REFRESHCOOKIE: "eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..81rfFfZkvTFSusDn.n8N0RE1fAku_wn_YnyYSBYCXzrlrv1u6N2n061_7PENsj-FgMLgd1RTS5gFwXVOKpQXdDwL9OYipau-r-VFRMgQjLhlzUD8jWJILCFhV0y61iDZYp6LQ3tb0fwB-0Ezx6oPg5g4GGp9_2iqOJfMzmqLgtiKHjJSEmf4vVRytjbfxAuNPuouAjT9KspVigNLUowgKf40dtt2PR-7OiWZRPo-O4cffhvDd23pTB5zx41yrEWNlSm3xFoTW4XYRyWEPjI5gY8nMMMCOsIoK87pbEUrTPrCnqBUJIObfiTPoh2siu3fS_iFALxDV-SePyVFYiHTCRIBN6mqkAfOzUghC6OkoIWyx0cyPfY3-OsnwwLjM0m5b4X-ftxZWWBbppfgjki0O3KNSE3iFUEFSESFGzcOSv1TX8zBqj1pkqpnLmhTbger7KY_ORNWWLBMmPM3k0WOZtjd7_vQk3GxGA5mHQ16R-rO-cDhvRjf55wPOjNnRLXnz16i1XjBRRRxwFNES-O2XCxodmH0l36mDLFnRT3DYkDBC9dmVlRzIBsql2GhBn8IdL9Kg2A-AXjAbq0VnRFRdGQW3QW0Be7K9VlqGmxSXQhabaAy2fvUk1lVDOJ6flLjicLLCpkpYa5XA2AXz0fbkM9EhmRE5WaNgCKIDQ3lBkghLgtuAquEkUU-DDnB276UmbejnYPAVb5pagUSHIXbzcD1C_O2wQr_MFHK0ty7BaeG6350P-FGPrRu8CQtW-0pf6u5TURKGj6L69LCkiMF_fl3z_s1QbbtTg0Ppk4G7o_6CbbZe9Fw1CRUTyX5EN0u4LKVwLMqNL3xT9OeS81N3djzFbpRXhKwp9poGZOeX7j3ZYs6znXltpZfVfO2JdIOxTjP-fqQw3d3dp93i6POaWmlkgEk0WobG9yPHVDBBIzt3h3Je9Ty7vjmXQAC6wQHLX7YjSiqm4mIK9IGosRSL_3C2n3FUVNWKuczatJBpNKdIGuxF4SBFzLHVJFQQNhKM9GkjMJdqXhIPFdKzvLqb9WVR1jh3GQ-W6McV0deiM6LzvkMNK7vo_qKq3LUqzTIKZpxYfrCNaOS5msZQoNsRA0WRcreIRH8w6JFls9l4eINDkUDq5dCtL3S_hXuacgIm-kNCMqTJWtXd6qXLpnMT4Z2mjU0LnhoZpBKrflAfNFypNgkCaGjX3Z8aPo_AKnYfOxzXAkLmfTr-_ipoLA7NRw6RtKdc68VBOfl0Lf_k3LusXvtJgO2S2Gfy7T34h7GiR-_Yh87x7of07r0q0r1O1BHD-Exxp9u1EFpA3QldW0Ni5uv82aYRpFmKc1xrt3_V3BJpcazYLd4OjnWLqxY2qpYBqw42NfISrqe3nHkkvOK5c9YtQpScLbimVh_70eMbdZi9Bx3wffROa1Ju-MykseVN1Jln97q4EFZ9VnWHYgoyp2pxSfcFL8PeNhi0RvH8craC2W-HrmPEebk4N5MT_bL7P59sZOlm6UwBr5j7GVMQDay3h1ersTrVbyRze7WPODrTh6Z0olH7cfjw9GInEEyGrhNWmUJmq7ZYqMh0QzU0yLgkzDPZcGxkZtIZax292oUOF2HthxrFckm58A9paD18ypYuwYnfDh5zc2-ytA6VNX_65zJ4Mwf9jWkwXnPZ4_b74ct7Po8PrCczsBGNPTbogSMjYe0oMiiVnN3Ft4lEi4GrpQdmpBjdeiHxWtKoLWHeILzbaYp3k6lyivEqBmedner1vd6mYZelxJWTAz-ViWoonwx-MwfdLq70LBlKyMYOj0QJ8NfW8aUeTAK028RxCEx6mlzPgDWCamdo1InJeTzSBXiI80YYibY2WmhIxVmJtv8qRO4bNlOOR02ZEgiuC-4UduoYL_W1sbGNtXK79v5a58XVuThSLIjsX3pKiWNMMUzgjnHrzY01nHlsvPABFHwSjH5zmNgZh0nz3C6Ffio8P6qzxF1mJ1dHyb2dMKcOeVxT6ha3Dq8YZdiRBSZqKN63jHAh4n-QyQErO5GD2u7K6rtWz3-WLmmhEiuTKTtg4RyGY5v8_b5-uA0J_1WueBsSgvXRElu7iSPX70x1C2EMZ6eDmkFYbnf9ZDd1LaVp8S4EHDWyntgymA2g8hrT5E1XWjHWrG0G2_wIgkwzg1viFb6365hj1dnRrish6Ac7tXbuTbfnKRh23CrRfEu4202RST9B0TwD-wi7lWICkMN0lRnbPvJGu9aYiNnMnAOvuac0MCc-EmBsGxrxkRjgRgj_OBb9pu5Gim5n96V-CZL7XoeGcUqNVZcecqCxJwJceePOQ-Pbe0QcQTXGvbY7cAEIZPMkk-jhNahU5q8ao_J3e5ZqT_q2sSZwTeh9SQCULmVe4i_E5N3e_xL8e8RSW6gyoD6Q_9IglxDDkZctxWy7nxoOQTE9rEEi1d00MLRg3bp8dwPQ7jTwn2AbQXVkTot5Fh_AoJd5G_xgAe2BLCZFR3fyd84o5yubDfjBZuzJ2Btj86xmpGLZnjd3i8T_kRJ4EVpqBMQXoJRgsIQcZGOay3PVuVnZBgYpwK3EFlySrKpiUlVarCWa5_T6KhdFAw4BFzOLWyeMXNhKzTkA8SkoFAv_BukEdw3CrCMiPbyyqsPbz3z_8eWBBlsaQCkeHKxYIkv4p4_rKWzoWye3-F7pSVHUqPAWbjeU_1swcWG5k1NBUKg9fJcg0-Ai34As3_gGN_JSf058DWPaijHM7U0md3IzX1p7qFO09tD0HlZ4njkt_u4U9uDlNrWybkCqY8F_pYLK2waXbf16bOiu1tPdYWmKgHZy6Rwtq8AwnF6P3lWauo3LvDxVKJxSyMSvwz4jObZ7C6o0M66Npa_UM1NGqHOxIiXoAWeEOfDjiQOOBjyX5QgzGPOQovsS9kwgkkoBQeIb84jD4MkIzvJdX_egVWgUFiA_wgH91dhULjlqIuJOYA7EXJaCA0yf2mBny-hCB7oWvFY12vxaUnG90Tg9EZc-AOsi9qqUi7VZmefzuqnqecFEcPaGPvZCxIX6vAs_LVAWQQjg2tLutkEM9uDppwLzUjWa6cuNOagWXXZ6_Euiptm4kDmDjWon8aDlz60ciHDf-A.wYHjz3YIhi85NuwQURm2Eg"
# OAUTH_URL: https://xxxxx.xxx.com/ouath # oauth地址 用于集成第三方登录 默认值 ""
# LOGIN_CALLBACK: "/login" # 登录回调地址,用于指定自己的登录页面 默认值 "/login"
# ASSET_PREFIX: https://cdn.oaistatic.com # 静态资源前缀,用于指定自己的静态资源地址 默认值 https://oaistatic-cdn.closeai.biz
# ARKOSE_URL: https://tcr9i.chat.openai.com/v2/ # arkose地址,用于指定自己的arkose人机验证地址 默认值 https://tcr9i.closeai.biz/v2/
# ADMIN_PASSWORD: xxxxx # 管理员密码 默认值为随机字符串,每次启动都会变化，可以在启动时通过日志查看，也可以指定一个固定值，方便管理
# AUDIT_LIMIT_URL: https://auditlimit.closeai.biz/audit_limit # 审计限制url 默认值 ""

# 以下配置不兼容环境变量设置,只能通过配置文件设置
USERTOKENS: # 用户token,可配置多个,本项内容支持热更新,更改后即时生效
  - "user1"
  - "user2"

# PROXY: "http://127.0.0.1:31280"  # 代理地址
# OAUTH_URL: https://xxxxx.xxx.com/ouath

# 注意注意,以下为新增配置,如需自动创建数据库,必加以下配置
cool:
  autoMigrate: true


# sqlite数据库配置
database:
  default:
    type: "sqlite" # 数据库类型
    name: "./config/cool.sqlite" # 数据库名称,对于sqlite来说就是数据库文件名
    extra: busy_timeout=5000 # 扩展参数 如 busy_timeout=5000&journal_mode=ALL
    createdAt: "create_time" # 创建时间字段名称
    updatedAt: "update_time" # 更新时间字段名称
    # debug: true # 开启调试模式,启用后将在控制台打印相关sql语句

# mysql数据库配置

# database:
#   default: # 数据源名称,当不指定数据源时 default 为默认数据源
#     type: "mysql" # 数据库类型
#     host: "127.0.0.1" # 数据库地址
#     port: "3306" # 数据库端口
#     user: "root" # 数据库用户名
#     pass: "xxxxxxxxx" # 数据库密码
#     name: "cockroachai" # 数据库名称
#     charset: "utf8mb4" # 数据库编码
#     timezone: "Asia/Shanghai" # 数据库时区
#     # debug: true # 是否开启调试模式，开启后会打印SQL日志
#     createdAt: "createTime" # 创建时间字段
#     updatedAt: "updateTime" # 更新时间字段
